### ISSUE TITLE
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by viridius0** [ChuloAI/BrainChulo#39]
I get this error message with pip version of docker-compose 1.29.2.

I changed host to bridge in docker-compose.yaml but it can't communicate with the oobabooga api.

**Comment by paolorechia** [comment]
Hi, @viridius0 

As a workaround, did you try removing the port bindings but keeping the host network mode?

**Comment by viridius0** [comment]
Thanks, that worked.  FYI, I had to edit the Dockerfile and put a trailing / at the end of the directory /code so that this would build.  I got this message otherwise:

 ROR: Service 'frontend' failed to build: When using COPY with more than one source file, the destination must be a directory and end with a /

**Comment by paolorechia** [comment]
Cool! I think I don't see this issue because I'm using a different version of docker-compose:

```
(brain) paolo@paolo-MS-7D08:~/BrainChulo$ docker-compose -v
Docker Compose version v2.15.1
```
